services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "127.0.0.1:8200:8200"
      - "127.0.0.1:8201:8201"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root-token
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    volumes:
      - vault-data:/vault/file
      - ./vault/config.hcl:/vault/config/config.hcl:ro
    cap_add:
      - IPC_LOCK
    command: server -config=/vault/config/config.hcl
    networks:
      - vault-net

networks:
  vault-net:
    driver: bridge
    internal: true

volumes:
  vault-data:
